[workspace]

members = [
    "crates/base",
    "crates/xactor",
    "crates/xactor-derive",
    "crates/xactor-playground",
    "crates/db",
    "crates/crypto",
    "crates/server",
    "crates/server-app",
    "crates/client",
    "crates/client-app"
]
